services:
  postgres:
    image: postgres
    environment:
      - "POSTGRES_DB=mydatabase"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=myuser"
    expose:
      - "5432:5432"
  server:
    build:
      context: ./estore-microservice
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_started
        restart: true
  webapp:
    build:
      context: ./estore-frontend
    ports:
      - "3000:3000"
    image: webapp
    container_name: webapp
